### ISSUE TITLE
As a customer I want to sort services by location, price, categories.

### ISSUE THREAD

**Issue by rsolovev** [rsolovev/cross-service#12]
**Given**: I’m a logged in customer and I’m on the main page.

**When**: I choose “Location” from drop-down menu under the search button.
**Then**: Results found are shown sorted by location in alphabetical order.

**When**: I choose “Price” from drop-down menu under the search button.
**Then**: Results found are shown sorted by price from lowest price to highest.

**When**: I choose “Categories” from drop-down menu under the search button.
**Then**: Results found are shown sorted by Categories in alphabetical order.

**Comment by kckusal** [comment]
This was just a possible variant. We have already implemented the overall search, that should suffice.
