### ISSUE TITLE
As a user I want to be able to subscribe or unsubscribe to email and telegram notifications to receive information faster.

### ISSUE THREAD

**Issue by rsolovev** [rsolovev/cross-service#16]
**Given**: I’m a registered user of the system but currently not logged-in and a comment was given for one my requests.

**When**: I check my telegram account for updates.
**Then**: I can see a notification of comment given for one my requests.

**Comment by kckusal** [comment]
This was an extension to do if we had time, but since we don't, we are closing this for now. It may happen that we reopen this in future and continue working on it!
